// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO session (
  id,
  cwd,
  history_json
) VALUES (
  ?, ?, jsonb(?)
)
`

type CreateSessionParams struct {
	ID    int64
	Cwd   string
	Jsonb interface{}
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.ID, arg.Cwd, arg.Jsonb)
	return err
}

const getLatestSessionByCwd = `-- name: GetLatestSessionByCwd :one
SELECT
  id,
  cwd,
  json(history_json) AS history_json
FROM session
WHERE cwd = ?
ORDER BY id DESC
LIMIT 1
`

type GetLatestSessionByCwdRow struct {
	ID          int64
	Cwd         string
	HistoryJson interface{}
}

func (q *Queries) GetLatestSessionByCwd(ctx context.Context, cwd string) (GetLatestSessionByCwdRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestSessionByCwd, cwd)
	var i GetLatestSessionByCwdRow
	err := row.Scan(&i.ID, &i.Cwd, &i.HistoryJson)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT
  id,
  cwd,
  json(history_json) AS history_json
FROM session
WHERE cwd = ? AND id = ?
`

type GetSessionByIDParams struct {
	Cwd string
	ID  int64
}

type GetSessionByIDRow struct {
	ID          int64
	Cwd         string
	HistoryJson interface{}
}

func (q *Queries) GetSessionByID(ctx context.Context, arg GetSessionByIDParams) (GetSessionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionByID, arg.Cwd, arg.ID)
	var i GetSessionByIDRow
	err := row.Scan(&i.ID, &i.Cwd, &i.HistoryJson)
	return i, err
}

const listSessionsByCwd = `-- name: ListSessionsByCwd :many
SELECT
  id,
  cast(json_array_length(history_json) as int) AS message_count
FROM session
WHERE cwd = ?
ORDER BY id DESC
`

type ListSessionsByCwdRow struct {
	ID           int64
	MessageCount int64
}

func (q *Queries) ListSessionsByCwd(ctx context.Context, cwd string) ([]ListSessionsByCwdRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByCwd, cwd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsByCwdRow
	for rows.Next() {
		var i ListSessionsByCwdRow
		if err := rows.Scan(&i.ID, &i.MessageCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveSessionHistory = `-- name: SaveSessionHistory :exec
INSERT INTO session (
  id,
  cwd,
  history_json
) VALUES (
  ?, ?, jsonb(?)
)
ON CONFLICT (cwd, id) DO UPDATE SET
  history_json = excluded.history_json
`

type SaveSessionHistoryParams struct {
	ID    int64
	Cwd   string
	Jsonb interface{}
}

func (q *Queries) SaveSessionHistory(ctx context.Context, arg SaveSessionHistoryParams) error {
	_, err := q.db.ExecContext(ctx, saveSessionHistory, arg.ID, arg.Cwd, arg.Jsonb)
	return err
}
